spring.application.name=servicio-asistencia

server.port=8082

# URL de conexión hacia la nueva base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/asistencia_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gestión de tablas (creará la tabla basándose en la entidad Asistencia)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true