spring.application.name=colegio

server.port=8081

# URL de conexión (El puerto por defecto de Postgres es 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/colegio_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gestión de tablas (Muy importante durante el desarrollo)
# 'update' creará las tablas automáticamente basándose en tu clase @Entity Usuario
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola para debugear
spring.jpa.show-sql=true