spring.application.name=servicio-mensajeria
server.port=8086

# Configuración de base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/mensajeria_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configuración Resilience4j
resilience4j.circuitbreaker.instances.usuariosCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.usuariosCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.usuariosCB.waitDurationInOpenState=5s

# URLs externas
servicio.usuarios.url=${SERVICIO_USUARIOS_URL:http://127.0.0.1:8081}

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

