spring.application.name=apigateway

server.port=9090

# Ruta para servicio-usuarios (incluyendo auth y usuarios)
spring.cloud.gateway.routes[0].id=servicio-usuarios
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**,/api/auth/**

# Puedes agregar más rutas para otros servicios cuando estén implementados
spring.cloud.gateway.routes[1].id=servicio-asistencia
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/asistencia/**

spring.cloud.gateway.routes[2].id=servicio-matricula
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/matricula/**

# Ruta para servicio-academico
spring.cloud.gateway.routes[3].id=servicio-academico
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/academico/**
